services:
    instock-backend:
        container_name: instock-backend-app
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
          - 5000:5000
        volumes:
          - ./:/usr/src/
        environment:
          - PG_HOST=postgres
          - PG_PORT=5432
          - PG_USER=inciclemaster
          - PG_PASSWORD=incicle-pass
          - PG_DB_NAME=incicle
          - PORT=5000
        networks:
          - laravel-network
networks:
  laravel-network:
      external: true