services:
    instock-backend:
        container_name: instock-backend-app
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
          - 5000:5000
        volumes:
          - ./:/usr/src/
        environment:
          - PORT=5000
          - DB_HOST=postgres
          - DB_DATABASE=incicle
          - DB_USERNAME=inciclemaster
          - DB_PASSWORD=incicle-pass
          - JWT_SECRET=dEP1CRzlFR8LwqA3Nt96rupOarLM6Q6z
          - JWT_EXPIRES_IN=1d
        networks:
          - laravel-network
networks:
  laravel-network:
      external: true