services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
          - 5432:5432
        environment:
          PG_DB_NAME: local
          POSTGRES_USER: instockmaster
          POSTGRES_PASSWORD: instock-pass
          PGDATA: /var/lib/postgresql/data
        networks:
          - laravel-network
    redis:
      image: redis
      restart: always
      ports:
        - 6379:6379
      environment:
        - REDIS_PORT=6379
      networks:
        - laravel-network
networks:
    laravel-network:
        external: true