services:
    instock-backend:
        container_name: instock-backend-app
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
          - 5000:5000
        networks:
          - instock-network
        volumes:
          - ./:/usr/src/
        environment:
          - PG_HOST=postgres
          - PG_PORT=5432
          - PG_USER=instockmaster
          - PG_PASSWORD=instock-pass
          - PG_DB_NAME=local
networks:
    instock-network:
        external: true