services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
          - 5432:5432
        environment:
          PG_DB_NAME: postgres
          POSTGRES_USER: instockmaster
          POSTGRES_PASSWORD: instock-pass
          PGDATA: /var/lib/postgresql/data
        networks:
          - instock-network
networks:
    instock-network:
        external: true